excludes:
  paths:
    - pattern: "**/src/*/test/**"
      reason: "TEST_OF"
      comment: "Unit test files"
    - pattern: "**/tests/**"
      reason: "TEST_OF"
      comment: "Test suite files"
    - pattern: "**/spec/**"
      reason: "TEST_OF"
      comment: "Specification/test files"
    - pattern: "**/.test/**"
      reason: "TEST_OF"
      comment: "Hidden test directories"
    - pattern: "*/package-managers/cocoapods/**"
      reason: "TEST_TOOL_OF"
      comment: "Conflicting OTP project test assets"
package_managers:
  Mix:
    enabled: true
    path_includes:
      - "src/elixir/**"
      - "apps/*/mix.exs"
      - "**/mix.exs"
    path_excludes:
      - "src/erlang/**"
      - "**/rebar.config"
      - "**/rebar.lock"
  Rebar3:
    enabled: false
    path_includes:
      - "src/erlang/**"
      - "**/rebar.config"
      - "**/rebar.lock"
    path_excludes:
      - "src/elixir/**"
      - "**/mix.exs"
      - "**/mix.lock"
scanner:
  skip_colored: true
  skip_excluded: true
  package_managers:
    - Npm
    - Pip
    - Gradle
    - Maven
    - Mix
analyzer:
  skip_excluded: true