name: ORT Configuration
version: 2.0
excludes:
  paths:
    - pattern: "**/src/*/test/**"
      reason: "TEST_OF"
      comment: "Unit test files"
    - pattern: "**/tests/**"
      reason: "TEST_OF"
      comment: "Test suite files"
    - pattern: "**/spec/**"
      reason: "TEST_OF"
      comment: "Specification/test files"
    - pattern: "**/.test/**"
      reason: "TEST_OF"
      comment: "Hidden test directories"
    - pattern: "*/package-managers/cocoapods/**"
      reason: "TEST_TOOL_OF"
      comment: "Conflicting OTP project test assets"
packageManagers:
  Mix:
    enabled: true
    pathIncludes:
      - "src/elixir/**"
      - "apps/*/mix.exs"
      - "**/mix.exs"
    pathExcludes:
      - "src/erlang/**"
      - "**/rebar.config"
      - "**/rebar.lock"
  Rebar3:
    enabled: false
    pathIncludes:
      - "src/erlang/**"
      - "**/rebar.config"
      - "**/rebar.lock"
    pathExcludes:
      - "src/elixir/**"
      - "**/mix.lock"
scanner:
  skipExcluded: true
  packageManagers:
    - Npm
    - Pip
    - Gradle
    - Maven
    - Mix
analyzer:
  skipExcluded: true
